# Generated by Django 2.1.2 on 2019-12-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='password',
            field=models.CharField(max_length=256, verbose_name='用户密码'),
        ),
    ]
