# Generated by Django 2.1.2 on 2019-12-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(1, '货到付款'), (3, '支付宝'), (2, '微信支付'), (4, '银联支付')], default=1, verbose_name='支付方式'),
        ),
    ]
