# Generated by Django 2.1.2 on 2019-12-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20191219_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_method',
            field=models.SmallIntegerField(choices=[(4, '银联支付'), (1, '货到付款'), (2, '微信支付'), (3, '支付宝')], default=1, verbose_name='支付方式'),
        ),
    ]
